In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [31]:
dataset = pd.read_csv("final_data.csv")

In [32]:
dataset.head()

Unnamed: 0.1  Unnamed: 0  heart_rate  systole  diastole  risk
0             0           0          43      109        71     0
1             1           1         108      110        76     0
2             2           2         119      132        72     1
3             3           3         104      137        82     1
4             4           4          72      156        83     1

In [50]:
dataset.drop("Unnamed: 0.1", inplace=True, axis=1)

In [51]:
dataset.drop("Unnamed: 0", inplace=True, axis=1)

In [53]:
dataset.head()

heart_rate  systole  diastole  risk
0          43      109        71     0
1         108      110        76     0
2         119      132        72     1
3         104      137        82     1
4          72      156        83     1

In [54]:
X = dataset.iloc[:, :3].values
y = dataset.iloc[:, -1:].values

In [55]:
print(X)

[[ 43 109  71]
 [108 110  76]
 [119 132  72]
 ...
 [100 119  66]
 [ 89 135  60]
 [113 166  74]]


In [56]:
print(y)

[[0]
 [0]
 [1]
 ...
 [0]
 [1]
 [1]]


In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [58]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
# Training the logistic regression model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/Users/ongtjunjet/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [60]:
y_pred = classifier.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [0 1]
 [1 1]
 ...
 [1 1]
 [0 0]
 [1 1]]


In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 469  127]
 [  99 1805]]
0.9096


In [ ]:
systole_reading = 0
diastole_reading = 0
heart_rate = 0
result = classifier.predict(sc.transform([[heart_rate, systole_reading, diastole_reading]]))
if (result[0] == 0):
    print("Healthy")
else:
    print("High Risk of Hypertension")